import { createCatalog } from './localization.js';

export const ENGLISH_CATALOG = createCatalog('en', {
  common: {
    back: 'Back',
    cancel: 'Cancel',
    close: 'Close',
    confirm: 'Confirm',
    continue: 'Continue',
    disabled: 'Unavailable',
    done: 'Done',
    loading: 'Loading…',
    next: 'Next',
    none: 'None',
    previous: 'Previous',
    reset: 'Reset',
    retry: 'Retry',
    save: 'Save',
    settings: 'Settings',
  },
  app: {
    title: 'Fields of Resolve',
    subtitle: 'A fictional operational RTS',
    language: 'Language',
    english: 'English',
    ukrainian: 'Ukrainian',
    unsupportedLocale: 'This language is not available. English is being used.',
  },
  operations: {
    heading: 'Operations',
    start: 'Start operation',
    restart: 'Restart operation',
    resume: 'Resume operation',
    quit: 'Quit to operations',
    locked: 'Complete the prerequisite operation to unlock this mission.',
    count: {
      one: '{count} operation',
      other: '{count} operations',
    },
  },
  mission: {
    briefing: 'Mission briefing',
    objectives: 'Objectives',
    optional: 'Optional',
    completed: 'Completed',
    failed: 'Failed',
    victory: 'Victory',
    defeat: 'Defeat',
    elapsed: 'Elapsed: {time}',
    objectiveProgress: '{completed} of {total} objectives complete',
  },
  commandCard: {
    label: 'Unit and facility command card',
    page: 'Command card page {page} of {pages}',
    pages: 'Command card pages',
    targeting: 'Targeting',
    groups: {
      orders: 'Orders',
      targeting: 'Targeting',
      stances: 'Stances',
      abilities: 'Abilities',
      construction: 'Construction',
      production: 'Production',
      modernization: 'Modernization',
    },
    unavailable: 'This command is unavailable for the current selection or state.',
    coolingDown: '{command} is cooling down for {time}.',
    requiresArmedUnit: 'Select at least one armed Ukrainian unit.',
    requiresDamagedVehicle: 'Select at least one damaged vehicle.',
    requiresRepairFacility: 'No operational repair workshop is available.',
  },
  resources: {
    metal: 'Metal',
    fuel: 'Fuel',
    intel: 'Intel',
    capacity: 'Command capacity',
    income: '{resource}: +{amount}/min',
    amount: '{resource}: {amount}',
    workers: {
      one: '{count} worker',
      other: '{count} workers',
    },
  },
  alerts: {
    heading: 'Alerts',
    underAttack: '{name} is under attack.',
    objectiveUpdated: 'Objective updated: {objective}',
    productionComplete: 'Production complete: {name}',
    researchComplete: 'Research complete: {name}',
    saved: 'Game saved.',
    history: 'Message history',
    unread: {
      one: '{count} unread alert',
      other: '{count} unread alerts',
    },
  },
  technology: {
    heading: 'Technology tree',
    available: 'Available',
    researching: 'Researching',
    completed: 'Researched',
    locked: 'Locked',
    cost: 'Cost: {cost}',
    duration: 'Research time: {time}',
    prerequisite: 'Requires: {name}',
  },
  accessibility: {
    dialog: 'Accessibility',
    reducedMotion: 'Reduce motion',
    highContrast: 'High contrast',
    subtitles: 'Subtitles',
    visualAudioCues: 'Visual audio cues',
    textScale: 'Text scale',
    uiScale: 'Interface scale',
  },
  errors: {
    generic: 'Something went wrong.',
    storageUnavailable: 'Local storage is unavailable. Changes will last for this session only.',
    missingTranslation: 'Missing translation: {key}',
  },
});

export const UKRAINIAN_CATALOG = createCatalog('uk', {
  common: {
    back: 'Назад',
    cancel: 'Скасувати',
    close: 'Закрити',
    confirm: 'Підтвердити',
    continue: 'Продовжити',
    disabled: 'Недоступно',
    done: 'Готово',
    loading: 'Завантаження…',
    next: 'Далі',
    none: 'Немає',
    previous: 'Назад',
    reset: 'Скинути',
    retry: 'Повторити',
    save: 'Зберегти',
    settings: 'Налаштування',
  },
  app: {
    title: 'Поля рішучості',
    subtitle: 'Вигадана оперативна стратегія',
    language: 'Мова',
    english: 'Англійська',
    ukrainian: 'Українська',
    unsupportedLocale: 'Ця мова недоступна. Використовується англійська.',
  },
  operations: {
    heading: 'Операції',
    start: 'Почати операцію',
    restart: 'Почати операцію знову',
    resume: 'Продовжити операцію',
    quit: 'Вийти до операцій',
    locked: 'Завершіть попередню операцію, щоб відкрити цю місію.',
    count: {
      one: '{count} операція',
      few: '{count} операції',
      many: '{count} операцій',
      other: '{count} операції',
    },
  },
  mission: {
    briefing: 'Брифінг місії',
    objectives: 'Завдання',
    optional: 'Необов’язково',
    completed: 'Виконано',
    failed: 'Провалено',
    victory: 'Перемога',
    defeat: 'Поразка',
    elapsed: 'Час: {time}',
    objectiveProgress: 'Виконано завдань: {completed} з {total}',
  },
  commandCard: {
    label: 'Панель команд підрозділу або споруди',
    page: 'Сторінка команд {page} з {pages}',
    pages: 'Сторінки команд',
    targeting: 'Вибір цілі',
    groups: {
      orders: 'Накази',
      targeting: 'Наведення',
      stances: 'Режими вогню',
      abilities: 'Здібності',
      construction: 'Будівництво',
      production: 'Виробництво',
      modernization: 'Модернізація',
    },
    unavailable: 'Ця команда недоступна для поточного вибору або стану.',
    coolingDown: 'Команда «{command}» відновлюється ще {time}.',
    requiresArmedUnit: 'Виберіть щонайменше один озброєний український підрозділ.',
    requiresDamagedVehicle: 'Виберіть щонайменше одну пошкоджену машину.',
    requiresRepairFacility: 'Немає справної ремонтної майстерні.',
  },
  resources: {
    metal: 'Метал',
    fuel: 'Пальне',
    intel: 'Розвіддані',
    capacity: 'Ліміт командування',
    income: '{resource}: +{amount}/хв',
    amount: '{resource}: {amount}',
    workers: {
      one: '{count} робітник',
      few: '{count} робітники',
      many: '{count} робітників',
      other: '{count} робітника',
    },
  },
  alerts: {
    heading: 'Сповіщення',
    underAttack: '{name} атакують.',
    objectiveUpdated: 'Завдання оновлено: {objective}',
    productionComplete: 'Виробництво завершено: {name}',
    researchComplete: 'Дослідження завершено: {name}',
    saved: 'Гру збережено.',
    history: 'Історія повідомлень',
    unread: {
      one: '{count} непрочитане сповіщення',
      few: '{count} непрочитані сповіщення',
      many: '{count} непрочитаних сповіщень',
      other: '{count} непрочитаного сповіщення',
    },
  },
  technology: {
    heading: 'Дерево технологій',
    available: 'Доступно',
    researching: 'Досліджується',
    completed: 'Досліджено',
    locked: 'Заблоковано',
    cost: 'Вартість: {cost}',
    duration: 'Час дослідження: {time}',
    prerequisite: 'Потрібно: {name}',
  },
  accessibility: {
    dialog: 'Доступність',
    reducedMotion: 'Зменшити рух',
    highContrast: 'Високий контраст',
    subtitles: 'Субтитри',
    visualAudioCues: 'Візуальні звукові сигнали',
    textScale: 'Масштаб тексту',
    uiScale: 'Масштаб інтерфейсу',
  },
  errors: {
    generic: 'Сталася помилка.',
    storageUnavailable: 'Локальне сховище недоступне. Зміни діятимуть лише в цьому сеансі.',
    missingTranslation: 'Відсутній переклад: {key}',
  },
});

export const LOCALIZATION_CATALOGS = Object.freeze([ENGLISH_CATALOG, UKRAINIAN_CATALOG]);
