export const TEAM={UA:0,RU:1};
export const WORLD={w:2560,h:1664,tile:32};
export const REGIONS={donbas:{name:'Donbas operational sector',subtitle:'Siverskyi Donets line',terrain:'industrial steppe'},zaporizhzhia:{name:'Zaporizhzhia axis',subtitle:'Orikhiv–Tokmak approach',terrain:'open steppe and shelterbelts'},kherson:{name:'Kherson bridgehead',subtitle:'Dnipro right-bank sector',terrain:'floodplain and villages'}};
export const UNIT_TYPES={
 sapper:{name:'Інженерно-саперне відділення',short:'Combat Engineers',role:'Engineering squad',hp:78,speed:63,range:60,damage:6,rate:1.05,sight:190,cost:{metal:65},pop:1,size:10,worker:true,abilities:['repair','buildDepot','buildBarracks']},
 mechanized:{name:'Механізоване відділення',short:'Mechanized Squad',role:'Dismounted infantry',hp:112,speed:60,range:155,damage:13,rate:.95,sight:230,cost:{metal:85},pop:2,size:12,abilities:['grenade','digIn']},
 fpv:{name:'Ударний FPV-розрахунок',short:'FPV Strike Team',role:'Unmanned strike system',hp:58,speed:116,range:240,damage:27,rate:1.8,sight:345,cost:{metal:75,fuel:42},pop:2,size:10,air:true,abilities:['reconPulse','strike']},
 medic:{name:'Медична евакуаційна група',short:'CASEVAC Team',role:'Combat lifesavers',hp:82,speed:65,range:110,damage:0,rate:.8,sight:220,cost:{metal:75,intel:15},pop:2,size:11,medic:true,abilities:['fieldDress','smoke']},
 m2:{name:'M2A2 Bradley ODS-SA',short:'Bradley IFV',role:'Mechanized infantry fighting vehicle',hp:305,speed:50,range:195,damage:31,rate:1.9,sight:265,cost:{metal:190,fuel:100},pop:4,size:19,armor:true,vehicleClass:'ifv',abilities:['suppress','deployInfantry']},
 t64:{name:'Т-64БВ обр. 2017',short:'T-64BV',role:'Main battle tank',hp:390,speed:44,range:215,damage:38,rate:2.15,sight:255,cost:{metal:235,fuel:135},pop:5,size:22,armor:true,vehicleClass:'tank',abilities:['smokeLaunchers']},
 bohDana:{name:'2С22 «Богдана»',short:'Bohdana SPH',role:'155 mm self-propelled artillery',hp:180,speed:39,range:365,damage:58,rate:3.35,sight:220,cost:{metal:225,fuel:125},pop:5,size:20,armor:true,vehicleClass:'artillery',abilities:['barrage']},
 zelensky:{name:'Volodymyr Zelenskyy',title:'Supreme Commander-in-Chief',hp:190,speed:62,range:140,damage:10,rate:1.1,sight:290,cost:{intel:180},pop:4,size:14,hero:true,abilities:['rally','address']},
 zaluzhnyi:{name:'Valerii Zaluzhnyi',title:'Commander',hp:215,speed:58,range:170,damage:18,rate:.9,sight:305,cost:{intel:210},pop:4,size:15,hero:true,abilities:['combinedArms','counterBattery']},
 motorRifle:{name:'Мотострілецьке відділення',short:'Motor Rifle Squad',hp:95,speed:58,range:142,damage:10,rate:1.05,sight:210,cost:{metal:0},pop:0,size:12,abilities:[]},
 stormZ:{name:'Штурмовий загін «Z»',short:'Storm-Z Detachment',hp:128,speed:63,range:148,damage:14,rate:.9,sight:225,cost:{metal:0},pop:0,size:13,abilities:['rush']},
 t72:{name:'Т-72Б3М',short:'T-72B3M',hp:365,speed:43,range:205,damage:35,rate:2.2,sight:245,cost:{metal:0},pop:0,size:21,armor:true,vehicleClass:'tank',abilities:[]},
 putin:{name:'Vladimir Putin',title:'Kremlin political command',hp:220,speed:55,range:145,damage:12,rate:1,sight:270,cost:{},pop:0,size:15,hero:true,abilities:['mobilize','propaganda']},
 prigozhin:{name:'Yevgeny Prigozhin',title:'PMC field leader',hp:240,speed:65,range:150,damage:22,rate:.8,sight:260,cost:{},pop:0,size:16,hero:true,abilities:['mercenaryWave','mutiny']}
};
export const BUILDING_TYPES={hq:{name:'Пункт управління бригади',hp:1500,w:108,h:88,sight:310},depot:{name:'Польовий склад МТЗ',hp:680,w:78,h:64,sight:195,pop:8},barracks:{name:'Район зосередження піхоти',hp:840,w:88,h:70,sight:215},workshop:{name:'Ремонтно-відновлювальний пункт',hp:980,w:98,h:74,sight:225}};
export const UPGRADES={
 cageArmor:{name:'Протидроновий захист',tier:1,applies:['tank','ifv'],cost:{metal:140,intel:40},desc:'+18% vehicle hit points; reduced FPV damage.',mods:{hp:1.18,droneResistance:.25}},
 thermal:{name:'Тепловізійні приціли',tier:1,applies:['tank','ifv'],cost:{metal:110,intel:65},desc:'+35 sight and +10% weapon range.',mods:{sight:35,range:1.1}},
 natoAmmo:{name:'Номенклатура НАТО 155 мм',tier:1,applies:['artillery'],cost:{metal:150,fuel:55,intel:45},desc:'+16% artillery damage and range.',mods:{damage:1.16,range:1.16}},
 activeProtection:{name:'Комплекс активного захисту',tier:2,requires:'cageArmor',applies:['tank'],cost:{metal:220,fuel:90,intel:90},desc:'+22% tank durability.',mods:{hp:1.22}},
 digitalC2:{name:'Цифровий контур управління',tier:2,requires:'thermal',applies:['tank','ifv','artillery'],cost:{metal:180,intel:120},desc:'Faster reloads and improved target acquisition.',mods:{rate:.84,sight:25}},
 mineRoller:{name:'Мінний трал КМТ',tier:2,applies:['tank'],cost:{metal:130,fuel:70},desc:'+12% movement speed on contested ground.',mods:{speed:1.12}}
};
export const ABILITIES={grenade:{name:'Ручна граната',key:'G',desc:'Area damage against a fire team.'},reconPulse:{name:'Повітряна розвідка',key:'R',desc:'Reveal a broad tactical area.'},strike:{name:'FPV ураження',key:'F',desc:'Heavy precision damage to one target.'},fieldDress:{name:'Стабілізація поранених',key:'H',desc:'Restore nearby friendly squads.'},rally:{name:'Звернення до підрозділів',key:'R',desc:'Raise morale and movement speed.'},address:{name:'Стратегічна комунікація',key:'A',desc:'Generate intelligence and morale.'},combinedArms:{name:'Загальновійськова взаємодія',key:'C',desc:'Boost a mixed tactical group.'},counterBattery:{name:'Контрбатарейна боротьба',key:'B',desc:'Strike hostile artillery positions.'},buildDepot:{name:'Розгорнути склад МТЗ',key:'1',desc:'Adds command and logistics capacity.'},buildBarracks:{name:'Облаштувати район піхоти',key:'2',desc:'Enables infantry training.'},deployInfantry:{name:'Спішити десант',key:'I',desc:'Deploy a mechanized infantry squad.'},barrage:{name:'Вогневий наліт',key:'B',desc:'Long-range 155 mm fire mission.'},smokeLaunchers:{name:'Димова завіса',key:'S',desc:'Temporarily reduce incoming accuracy.'}};
export const MISSIONS=[
 {id:'donbas',region:'donbas',title:'1. Сіверський Донець: Утримати переправу',story:'A battalion tactical group probes the Siverskyi Donets crossing. Establish a brigade support area, reinforce the treeline, and deny the bridgehead.',objectives:['Видобути 500 од. матеріалів','Розгорнути район піхоти та ремонтний пункт','Знищити передовий пункт управління'],start:{metal:200,fuel:90,intel:25},heroes:['zelensky'],enemyHeroes:[]},
 {id:'zaporizhzhia',region:'zaporizhzhia',title:'2. Оріхівський напрямок: Очі в небі',story:'Enemy batteries cover the Orikhiv–Tokmak axis. Build an unmanned-systems group, establish reconnaissance coverage, and conduct counter-battery work.',objectives:['Накопичити 250 розвідувальних даних','Розгорнути 4 FPV-розрахунки','Знищити всі артилерійські батареї'],start:{metal:280,fuel:165,intel:50},heroes:['zaluzhnyi'],enemyHeroes:['prigozhin']},
 {id:'kherson',region:'kherson',title:'3. Дніпровський плацдарм: Довга ніч',story:'A contested bridgehead on the lower Dnipro must survive repeated assault groups before the counterattack toward the left bank.',objectives:['Зібрати обох українських командирів','Відбити 6 штурмових хвиль','Знищити ворожий командний бункер'],start:{metal:380,fuel:240,intel:130},heroes:['zelensky','zaluzhnyi'],enemyHeroes:['putin','prigozhin']}
];