export const TEAM = { UA: 0, RU: 1 };
export const WORLD = { w: 2560, h: 1664, tile: 32 };

export const FACTIONS = {
  [TEAM.UA]: {
    id: 'ukraine',
    name: 'Ukraine',
    short: 'UA',
    primary: '#3978ad',
    secondary: '#e0c75b',
    marking: 'cross',
  },
  [TEAM.RU]: {
    id: 'russia',
    name: 'Russia',
    short: 'RU',
    primary: '#7c5043',
    secondary: '#c9b998',
    marking: 'chevron',
  },
};

export const REGIONS = {
  donbas: {
    name: 'Donbas operational sector',
    subtitle: 'Siverskyi Donets line',
    terrain: 'industrial steppe',
  },
  zaporizhzhia: {
    name: 'Zaporizhzhia axis',
    subtitle: 'Orikhiv–Tokmak approach',
    terrain: 'open steppe and shelterbelts',
  },
  kherson: {
    name: 'Kherson bridgehead',
    subtitle: 'Lower Dnipro sector',
    terrain: 'floodplain and villages',
  },
};

const unit = (faction, archetype, name, short, role, stats) => ({
  faction,
  archetype,
  name,
  short,
  role,
  ...stats,
});

export const UNIT_TYPES = {
  uaEngineer: unit(
    'ukraine',
    'engineer',
    'Ukrainian Combat Engineer Section',
    'Combat Engineers',
    'Construction, repair, and field logistics',
    {
      hp: 78,
      speed: 63,
      range: 60,
      damage: 6,
      rate: 1.05,
      sight: 190,
      cost: { metal: 65 },
      pop: 1,
      size: 10,
      worker: true,
      visual: 'uaEngineer',
      abilities: ['repair', 'buildDepot', 'buildBarracks', 'buildWorkshop'],
    },
  ),
  uaInfantry: unit(
    'ukraine',
    'infantry',
    'Ukrainian Mechanized Infantry Squad',
    'Mechanized Squad',
    'Dismounted line infantry',
    {
      hp: 112,
      speed: 60,
      range: 155,
      damage: 13,
      rate: 0.95,
      sight: 230,
      cost: { metal: 85 },
      pop: 2,
      size: 12,
      visual: 'uaInfantry',
      abilities: ['grenade', 'digIn'],
    },
  ),
  uaDrone: unit(
    'ukraine',
    'drone',
    'Ukrainian FPV Strike Team',
    'FPV Strike Team',
    'Fast precision unmanned strike element',
    {
      hp: 58,
      speed: 116,
      range: 240,
      damage: 27,
      rate: 1.8,
      sight: 345,
      cost: { metal: 75, fuel: 42 },
      pop: 2,
      size: 10,
      air: true,
      visual: 'quadDrone',
      abilities: ['reconPulse', 'strike'],
    },
  ),
  uaMedic: unit(
    'ukraine',
    'medic',
    'Ukrainian CASEVAC Team',
    'CASEVAC Team',
    'Combat lifesavers and casualty evacuation',
    {
      hp: 82,
      speed: 65,
      range: 110,
      damage: 0,
      rate: 0.8,
      sight: 220,
      cost: { metal: 75, intel: 15 },
      pop: 2,
      size: 11,
      medic: true,
      visual: 'uaMedic',
      abilities: ['fieldDress', 'smoke'],
    },
  ),
  uaIfv: unit(
    'ukraine',
    'ifv',
    'M2A2 Bradley ODS-SA',
    'Bradley IFV',
    'Mechanized infantry fighting vehicle',
    {
      hp: 305,
      speed: 50,
      range: 195,
      damage: 31,
      rate: 1.9,
      sight: 265,
      cost: { metal: 190, fuel: 100 },
      pop: 4,
      size: 19,
      armor: true,
      vehicleClass: 'ifv',
      visual: 'bradley',
      abilities: ['suppress', 'deployInfantry'],
    },
  ),
  uaTank: unit(
    'ukraine',
    'tank',
    'T-64BV Model 2017',
    'T-64BV',
    'Ukrainian main battle tank',
    {
      hp: 390,
      speed: 44,
      range: 215,
      damage: 38,
      rate: 2.15,
      sight: 255,
      cost: { metal: 235, fuel: 135 },
      pop: 5,
      size: 22,
      armor: true,
      vehicleClass: 'tank',
      visual: 't64',
      abilities: ['smokeLaunchers'],
    },
  ),
  uaArtillery: unit(
    'ukraine',
    'artillery',
    '2S22 Bohdana',
    'Bohdana SPH',
    '155 mm self-propelled artillery',
    {
      hp: 180,
      speed: 39,
      range: 365,
      damage: 58,
      rate: 3.35,
      sight: 220,
      cost: { metal: 225, fuel: 125 },
      pop: 5,
      size: 20,
      armor: true,
      vehicleClass: 'artillery',
      visual: 'bohdana',
      abilities: ['barrage'],
    },
  ),
  ruEngineer: unit(
    'russia',
    'engineer',
    'Russian Engineer-Sapper Section',
    'Engineer-Sappers',
    'Construction, repair, and obstacle clearance',
    {
      hp: 76,
      speed: 61,
      range: 60,
      damage: 6,
      rate: 1.05,
      sight: 185,
      cost: { metal: 0 },
      pop: 0,
      size: 10,
      worker: true,
      visual: 'ruEngineer',
      abilities: [],
    },
  ),
  ruInfantry: unit(
    'russia',
    'infantry',
    'Russian Motor Rifle Squad',
    'Motor Rifle Squad',
    'Dismounted line infantry',
    {
      hp: 100,
      speed: 58,
      range: 145,
      damage: 11,
      rate: 1.02,
      sight: 215,
      cost: { metal: 0 },
      pop: 0,
      size: 12,
      visual: 'ruInfantry',
      abilities: [],
    },
  ),
  ruDrone: unit(
    'russia',
    'drone',
    'Russian Lancet UAV Team',
    'Lancet UAV Team',
    'Loitering-munition strike element',
    {
      hp: 62,
      speed: 103,
      range: 255,
      damage: 30,
      rate: 2.1,
      sight: 320,
      cost: { metal: 0 },
      pop: 0,
      size: 11,
      air: true,
      visual: 'fixedWingDrone',
      abilities: [],
    },
  ),
  ruMedic: unit(
    'russia',
    'medic',
    'Russian Combat Medical Team',
    'Medical Team',
    'Forward treatment and casualty recovery',
    {
      hp: 84,
      speed: 61,
      range: 105,
      damage: 0,
      rate: 0.85,
      sight: 205,
      cost: { metal: 0 },
      pop: 0,
      size: 11,
      medic: true,
      visual: 'ruMedic',
      abilities: [],
    },
  ),
  ruIfv: unit(
    'russia',
    'ifv',
    'BMP-3 Infantry Fighting Vehicle',
    'BMP-3',
    'Tracked infantry fighting vehicle',
    {
      hp: 290,
      speed: 52,
      range: 190,
      damage: 33,
      rate: 2,
      sight: 250,
      cost: { metal: 0 },
      pop: 0,
      size: 19,
      armor: true,
      vehicleClass: 'ifv',
      visual: 'bmp3',
      abilities: [],
    },
  ),
  ruTank: unit(
    'russia',
    'tank',
    'T-72B3M Main Battle Tank',
    'T-72B3M',
    'Russian main battle tank',
    {
      hp: 370,
      speed: 43,
      range: 205,
      damage: 36,
      rate: 2.2,
      sight: 245,
      cost: { metal: 0 },
      pop: 0,
      size: 21,
      armor: true,
      vehicleClass: 'tank',
      visual: 't72',
      abilities: [],
    },
  ),
  ruArtillery: unit(
    'russia',
    'artillery',
    '2S19 Msta-S',
    'Msta-S SPH',
    '152 mm self-propelled artillery',
    {
      hp: 190,
      speed: 37,
      range: 350,
      damage: 55,
      rate: 3.45,
      sight: 215,
      cost: { metal: 0 },
      pop: 0,
      size: 20,
      armor: true,
      vehicleClass: 'artillery',
      visual: 'msta',
      abilities: [],
    },
  ),
  uaZelenskyy: unit(
    'ukraine',
    'hero',
    'Volodymyr Zelenskyy',
    'Zelenskyy',
    'Supreme Commander-in-Chief',
    {
      title: 'National Command',
      hp: 190,
      speed: 62,
      range: 140,
      damage: 10,
      rate: 1.1,
      sight: 290,
      cost: { intel: 180 },
      pop: 4,
      size: 14,
      hero: true,
      visual: 'uaHero',
      abilities: ['rally', 'address'],
    },
  ),
  uaZaluzhnyi: unit(
    'ukraine',
    'hero',
    'Valerii Zaluzhnyi',
    'Zaluzhnyi',
    'Senior military commander',
    {
      title: 'Strategic Command',
      hp: 215,
      speed: 58,
      range: 170,
      damage: 18,
      rate: 0.9,
      sight: 305,
      cost: { intel: 210 },
      pop: 4,
      size: 15,
      hero: true,
      visual: 'uaHero',
      abilities: ['combinedArms', 'counterBattery'],
    },
  ),
  ruPutin: unit(
    'russia',
    'hero',
    'Vladimir Putin',
    'Putin',
    'Russian political command',
    {
      title: 'National Command',
      hp: 220,
      speed: 55,
      range: 145,
      damage: 12,
      rate: 1,
      sight: 270,
      cost: {},
      pop: 0,
      size: 15,
      hero: true,
      visual: 'ruHero',
      abilities: ['mobilize', 'propaganda'],
    },
  ),
  ruPrigozhin: unit(
    'russia',
    'hero',
    'Yevgeny Prigozhin',
    'Prigozhin',
    'PMC field command',
    {
      title: 'PMC Command',
      hp: 240,
      speed: 65,
      range: 150,
      damage: 22,
      rate: 0.8,
      sight: 260,
      cost: {},
      pop: 0,
      size: 16,
      hero: true,
      visual: 'ruHero',
      abilities: ['mercenaryWave', 'mutiny'],
    },
  ),
};

export const BUILDING_TYPES = {
  hq: {
    name: 'Brigade Command Post',
    ruName: 'Regimental Command Post',
    desc: 'Command, engineering recruitment, and senior leadership.',
    hp: 1500,
    w: 108,
    h: 88,
    sight: 310,
    produces: ['uaEngineer'],
  },
  depot: {
    name: 'Field Logistics Depot',
    ruName: 'Forward Supply Depot',
    desc: 'Raises command capacity and anchors field logistics.',
    hp: 680,
    w: 78,
    h: 64,
    sight: 195,
    pop: 8,
    cost: { metal: 100 },
    buildTime: 7,
  },
  barracks: {
    name: 'Infantry Assembly Area',
    ruName: 'Motor Rifle Staging Area',
    desc: 'Produces infantry and CASEVAC teams.',
    hp: 840,
    w: 88,
    h: 70,
    sight: 215,
    cost: { metal: 150 },
    buildTime: 9,
    produces: ['uaInfantry', 'uaMedic'],
  },
  workshop: {
    name: 'Repair and Recovery Point',
    ruName: 'Armored Repair Point',
    desc: 'Produces drones, armored vehicles, and artillery; hosts modernization.',
    hp: 980,
    w: 98,
    h: 74,
    sight: 225,
    cost: { metal: 220, fuel: 80 },
    buildTime: 12,
    produces: ['uaDrone', 'uaIfv', 'uaTank', 'uaArtillery'],
  },
};

export const UPGRADES = {
  cageArmor: {
    name: 'Counter-UAS Roof Protection',
    tier: 1,
    applies: ['tank', 'ifv'],
    cost: { metal: 140, intel: 40 },
    desc: '+18% vehicle durability and reduced drone damage.',
    mods: { hp: 1.18, droneResistance: 0.25 },
  },
  thermal: {
    name: 'Thermal Fire-Control Sights',
    tier: 1,
    applies: ['tank', 'ifv'],
    cost: { metal: 110, intel: 65 },
    desc: '+35 sight and +10% weapon range.',
    mods: { sight: 35, range: 1.1 },
  },
  natoAmmo: {
    name: 'NATO 155 mm Ammunition',
    tier: 1,
    applies: ['artillery'],
    cost: { metal: 150, fuel: 55, intel: 45 },
    desc: '+16% artillery damage and range.',
    mods: { damage: 1.16, range: 1.16 },
  },
  activeProtection: {
    name: 'Active Protection Suite',
    tier: 2,
    requires: 'cageArmor',
    applies: ['tank'],
    cost: { metal: 220, fuel: 90, intel: 90 },
    desc: '+22% tank durability.',
    mods: { hp: 1.22 },
  },
  digitalC2: {
    name: 'Digital Battle Management',
    tier: 2,
    requires: 'thermal',
    applies: ['tank', 'ifv', 'artillery'],
    cost: { metal: 180, intel: 120 },
    desc: 'Faster reloads and improved target acquisition.',
    mods: { rate: 0.84, sight: 25 },
  },
  mineRoller: {
    name: 'KMT Mine-Roller Kit',
    tier: 2,
    applies: ['tank'],
    cost: { metal: 130, fuel: 70 },
    desc: '+12% vehicle movement speed.',
    mods: { speed: 1.12 },
  },
};

export const ABILITIES = {
  grenade: { name: 'Fragmentation Grenade', key: 'G', desc: 'Area damage against a fire team.' },
  reconPulse: { name: 'Aerial Reconnaissance', key: 'R', desc: 'Reveal a broad tactical area.' },
  strike: { name: 'FPV Precision Strike', key: 'F', desc: 'Heavy precision damage to one target.' },
  fieldDress: { name: 'Casualty Stabilization', key: 'H', desc: 'Restore nearby friendly squads.' },
  rally: { name: 'National Rally', key: 'R', desc: 'Raise nearby morale and movement speed.' },
  address: { name: 'Strategic Communication', key: 'A', desc: 'Generate intelligence and morale.' },
  combinedArms: { name: 'Combined-Arms Coordination', key: 'C', desc: 'Boost a mixed tactical group.' },
  counterBattery: { name: 'Counter-Battery Mission', key: 'B', desc: 'Strike hostile artillery positions.' },
  buildDepot: { name: 'Place Logistics Depot', key: '1', desc: 'Choose a battlefield location; adds command capacity.' },
  buildBarracks: { name: 'Place Infantry Area', key: '2', desc: 'Choose a battlefield location; enables infantry production.' },
  buildWorkshop: { name: 'Place Repair Workshop', key: '3', desc: 'Choose a battlefield location; unlocks specialized units.' },
  deployInfantry: { name: 'Dismount Infantry', key: 'I', desc: 'Deploy a mechanized infantry squad.' },
  barrage: { name: 'Artillery Fire Mission', key: 'B', desc: 'Long-range 155 mm bombardment.' },
  smokeLaunchers: { name: 'Smoke-Screen Launchers', key: 'S', desc: 'Temporarily reduce incoming accuracy.' },
};

export const MISSIONS = [
  {
    id: 'donbas',
    region: 'donbas',
    title: '1. Siverskyi Donets: Hold the Crossing',
    story:
      'A Russian mechanized group probes the Siverskyi Donets crossing. Establish a Ukrainian support area, reinforce the shelterbelt, and deny the bridgehead.',
    objectives: [
      'Recover 500 units of materiel',
      'Establish infantry and repair facilities',
      'Destroy the Russian forward command post',
    ],
    start: { metal: 240, fuel: 110, intel: 25 },
    heroes: ['uaZelenskyy'],
    trainableHeroes: [],
    enemyHeroes: [],
    waves: { firstDelay: 70, interval: 46, maxActive: 7, maxWaves: 7 },
  },
  {
    id: 'zaporizhzhia',
    region: 'zaporizhzhia',
    title: '2. Orikhiv Axis: Eyes Above',
    story:
      'Russian artillery covers the Orikhiv–Tokmak approach. Build a Ukrainian unmanned-systems group, establish reconnaissance coverage, and conduct counter-battery operations.',
    objectives: [
      'Accumulate 250 intelligence',
      'Field four Ukrainian FPV teams',
      'Destroy all Russian artillery batteries',
    ],
    start: { metal: 320, fuel: 190, intel: 70 },
    heroes: ['uaZaluzhnyi'],
    trainableHeroes: [],
    enemyHeroes: ['ruPrigozhin'],
    waves: { firstDelay: 58, interval: 42, maxActive: 9, maxWaves: 7 },
  },
  {
    id: 'kherson',
    region: 'kherson',
    title: '3. Lower Dnipro: The Long Night',
    story:
      'A Ukrainian bridgehead must survive six deliberate Russian assault groups before a counterattack toward the left bank.',
    objectives: [
      'Assemble both Ukrainian command heroes',
      'Defeat six Russian assault waves',
      'Destroy the Russian command bunker',
    ],
    start: { metal: 430, fuel: 260, intel: 230 },
    heroes: [],
    trainableHeroes: ['uaZelenskyy', 'uaZaluzhnyi'],
    enemyHeroes: ['ruPutin', 'ruPrigozhin'],
    waves: { firstDelay: 45, interval: 36, maxActive: 12, maxWaves: 6 },
  },
];
