export const TEAM={UA:0,RU:1};
export const WORLD={w:2560,h:1664,tile:32};
export const UNIT_TYPES={
 worker:{name:'Engineer Team',hp:70,speed:64,range:55,damage:5,rate:1.1,sight:180,cost:{metal:60},pop:1,size:10,worker:true,abilities:['repair','buildDepot','buildBarracks']},
 rifle:{name:'Rifle Section',hp:105,speed:61,range:150,damage:12,rate:1.0,sight:225,cost:{metal:80},pop:2,size:12,abilities:['grenade','digIn']},
 drone:{name:'FPV Drone',hp:55,speed:112,range:230,damage:25,rate:1.9,sight:330,cost:{metal:70,fuel:45},pop:2,size:10,air:true,abilities:['reconPulse','strike']},
 medic:{name:'Combat Medic',hp:78,speed:66,range:105,damage:0,rate:.8,sight:215,cost:{metal:75,intel:15},pop:2,size:11,medic:true,abilities:['fieldDress','smoke']},
 ifv:{name:'Infantry Fighting Vehicle',hp:285,speed:48,range:185,damage:29,rate:2.0,sight:250,cost:{metal:180,fuel:95},pop:4,size:18,armor:true,abilities:['suppress','deployInfantry']},
 artillery:{name:'Mobile Artillery',hp:165,speed:38,range:340,damage:52,rate:3.5,sight:210,cost:{metal:220,fuel:120},pop:5,size:19,armor:true,abilities:['barrage']},
 zelensky:{name:'Volodymyr Zelensky',title:'National Leader',hp:185,speed:62,range:140,damage:10,rate:1.1,sight:285,cost:{intel:180},pop:4,size:14,hero:true,abilities:['rally','address']},
 zaluzhnyi:{name:'Valerii Zaluzhnyi',title:'Commander-in-Chief',hp:210,speed:58,range:165,damage:18,rate:.9,sight:300,cost:{intel:210},pop:4,size:15,hero:true,abilities:['combinedArms','counterBattery']},
 conscript:{name:'Conscript Squad',hp:92,speed:58,range:140,damage:10,rate:1.05,sight:210,cost:{metal:0},pop:0,size:12,abilities:[]},
 storm:{name:'Storm Detachment',hp:125,speed:63,range:145,damage:14,rate:.9,sight:225,cost:{metal:0},pop:0,size:13,abilities:['rush']},
 tank:{name:'Main Battle Tank',hp:360,speed:42,range:205,damage:34,rate:2.2,sight:245,cost:{metal:0},pop:0,size:21,armor:true,abilities:[]},
 putin:{name:'Vladimir Putin',title:'Kremlin Leader',hp:220,speed:55,range:145,damage:12,rate:1.0,sight:270,cost:{},pop:0,size:15,hero:true,abilities:['mobilize','propaganda']},
 prigozhin:{name:'Yevgeny Prigozhin',title:'Warlord',hp:240,speed:65,range:150,damage:22,rate:.8,sight:260,cost:{},pop:0,size:16,hero:true,abilities:['mercenaryWave','mutiny']}
};
export const BUILDING_TYPES={hq:{name:'Command Headquarters',hp:1500,w:104,h:86,sight:300},depot:{name:'Supply Depot',hp:650,w:76,h:62,sight:190,pop:8},barracks:{name:'Field Barracks',hp:820,w:84,h:68,sight:210},workshop:{name:'Vehicle Workshop',hp:950,w:94,h:72,sight:220}};
export const ABILITIES={grenade:{name:'Grenade',key:'G',desc:'Area damage.'},reconPulse:{name:'Recon Pulse',key:'R',desc:'Reveal a large area.'},strike:{name:'Precision Strike',key:'F',desc:'Heavy target damage.'},fieldDress:{name:'Field Dressing',key:'H',desc:'Heal nearby allies.'},rally:{name:'National Rally',key:'R',desc:'Boost nearby allies.'},address:{name:'Address the Nation',key:'A',desc:'Generate intel and morale.'},combinedArms:{name:'Combined Arms',key:'C',desc:'Boost mixed forces.'},counterBattery:{name:'Counter-Battery',key:'B',desc:'Strike enemy artillery.'},buildDepot:{name:'Build Depot',key:'1',desc:'Adds command capacity.'},buildBarracks:{name:'Build Barracks',key:'2',desc:'Trains infantry.'},deployInfantry:{name:'Deploy Infantry',key:'I',desc:'Spawn a rifle section.'},barrage:{name:'Barrage',key:'B',desc:'Long-range bombardment.'}};
export const MISSIONS=[{id:'border',title:'1. Hold the Crossing',story:'A mechanized column presses toward a river crossing. Establish an economy, fortify the road, and hold until the counterattack is ready.',objectives:['Mine 500 metal','Build a barracks and workshop','Destroy the forward command post'],start:{metal:180,fuel:80,intel:20},heroes:['zelensky'],enemyHeroes:[]},{id:'sky',title:'2. Eyes Above',story:'Enemy artillery dominates the valley. Drones and signals intelligence must expose the guns before the armored push begins.',objectives:['Capture two signals stations','Field 4 drones','Eliminate all artillery batteries'],start:{metal:260,fuel:150,intel:45},heroes:['zaluzhnyi'],enemyHeroes:['prigozhin']},{id:'capital',title:'3. The Long Night',story:'The decisive battle. Unite the command structure, break successive attack waves, and seize the hostile headquarters.',objectives:['Recruit both Ukrainian heroes','Survive 6 assault waves','Destroy the Kremlin command bunker'],start:{metal:360,fuel:220,intel:120},heroes:['zelensky','zaluzhnyi'],enemyHeroes:['putin','prigozhin']}];