import {TEAM,WORLD,UNIT_TYPES,BUILDING_TYPES,MISSIONS,UPGRADES} from './config.js';
const rand=(a,b)=>a+Math.random()*(b-a),clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
export class Game{
 constructor(){this.camera={x:70,y:760,z:.85};this.keys=new Set();this.mouse={x:0,y:0,wx:0,wy:0,down:false,drag:false,startX:0,startY:0,attackMove:false};this.units=[];this.buildings=[];this.nodes=[];this.projectiles=[];this.effects=[];this.selected=new Set();this.nextId=1;this.time=0;this.wave=0;this.gameOver=false;this.terrain=[];this.road=[[120,1400],[540,1240],[960,1010],[1330,780],[1760,520],[2300,260]];this.mission=null}
 start(index=0){this.mission=MISSIONS[index];this.units=[];this.buildings=[];this.nodes=[];this.projectiles=[];this.effects=[];this.selected.clear();this.nextId=1;this.time=0;this.wave=0;this.gameOver=false;this.player={...this.mission.start,pop:0,cap:14,mined:0,objectives:[false,false,false],upgrades:new Set()};this.enemy={clock:12};this.terrain=[];for(let y=0;y<WORLD.h/32;y++)for(let x=0;x<WORLD.w/32;x++){const n=Math.sin(x*.41)+Math.cos(y*.31)+Math.sin((x+y)*.17);this.terrain.push(n>1.35?2:n<-1.48?1:0)}this.nodes.push({x:490,y:1280,kind:'metal',amount:1600,label:'Salvage Yard'},{x:760,y:1180,kind:'fuel',amount:1100,label:'Fuel Point'},{x:1120,y:850,kind:'intel',amount:900,label:'Signals Relay'},{x:1570,y:600,kind:'metal',amount:1800,label:'Industrial Site'},{x:1900,y:420,kind:'fuel',amount:1200,label:'Forward Fuel Base'});this.uaHQ=this.addBuilding('hq',TEAM.UA,230,1390);this.addBuilding('depot',TEAM.UA,350,1330);this.addBuilding('barracks',TEAM.UA,430,1430);this.ruHQ=this.addBuilding('hq',TEAM.RU,2300,260);this.addBuilding('barracks',TEAM.RU,2170,340);this.addBuilding('workshop',TEAM.RU,2230,175);[['uaEngineer',320,1380],['uaEngineer',355,1410],['uaInfantry',470,1360],['uaInfantry',500,1410]].forEach(a=>this.addUnit(a[0],TEAM.UA,a[1],a[2]));for(const h of this.mission.heroes)this.addUnit(h,TEAM.UA,390+rand(-25,25),1290+rand(-20,20));[['ruInfantry',2110,280],['ruInfantry',2070,330],['ruIfv',2140,300],['ruTank',2210,245]].forEach(a=>this.addUnit(a[0],TEAM.RU,a[1],a[2]));for(const h of this.mission.enemyHeroes)this.addUnit(h,TEAM.RU,2210+rand(-20,20),390+rand(-20,20));this.camera={x:innerWidth/2-390*.85,y:innerHeight/2-1320*.85,z:.85}}
 unitStats(type){const base=UNIT_TYPES[type],s={...base};for(const id of this.player?.upgrades||[]){const u=UPGRADES[id];if(base.vehicleClass&&u.applies.includes(base.vehicleClass)){if(u.mods.hp)s.hp*=u.mods.hp;if(u.mods.range)s.range*=u.mods.range;if(u.mods.damage)s.damage*=u.mods.damage;if(u.mods.speed)s.speed*=u.mods.speed;if(u.mods.rate)s.rate*=u.mods.rate;if(u.mods.sight)s.sight+=u.mods.sight}}return s}
 addUnit(type,team,x,y){const t=team===TEAM.UA?this.unitStats(type):UNIT_TYPES[type],u={id:this.nextId++,type,team,x,y,hp:t.hp,maxHp:t.hp,cool:rand(0,.4),abilityCd:{},order:null,target:null,selected:false,angle:0,flash:0,carry:0,carryKind:null,buffs:{},kills:0};this.units.push(u);if(team===TEAM.UA)this.player.pop+=t.pop||0;return u}
 addBuilding(type,team,x,y){const t=BUILDING_TYPES[type],b={id:this.nextId++,type,team,x,y,hp:t.hp,maxHp:t.hp,selected:false,queue:[]};this.buildings.push(b);if(team===TEAM.UA)this.player.cap+=t.pop||0;return b}
 worldPos(x,y){return{x:(x-this.camera.x)/this.camera.z,y:(y-this.camera.y)/this.camera.z}}
 selectedEntities(){return [...this.units,...this.buildings].filter(e=>this.selected.has(e.id))}
 selectedUnits(){return this.units.filter(u=>u.team===TEAM.UA&&this.selected.has(u.id))}
 hit(x,y){return [...this.units,...this.buildings].sort((a,b)=>b.y-a.y).find(e=>dist({x,y},e)<(e.maxHp>500?48:(UNIT_TYPES[e.type]?.size||12)+8))}
 select(e,add=false){if(!add){this.selected.clear();[...this.units,...this.buildings].forEach(x=>x.selected=false)}if(e){if(add&&this.selected.has(e.id)){this.selected.delete(e.id);e.selected=false}else{this.selected.add(e.id);e.selected=true}}}
 issue(x,y,target){const us=this.selectedUnits();if(!us.length)return;if(target&&target.team===TEAM.RU){us.forEach(u=>u.order={kind:'attack',target});return}const cols=Math.ceil(Math.sqrt(us.length));us.forEach((u,i)=>u.order={kind:this.mouse.attackMove?'attackMove':'move',x:x+((i%cols)-(cols-1)/2)*34,y:y+(Math.floor(i/cols)-Math.floor(us.length/cols)/2)*34});this.mouse.attackMove=false}
 canAfford(cost){return Object.entries(cost||{}).every(([k,v])=>this.player[k]>=v)} pay(cost){for(const[k,v]of Object.entries(cost||{}))this.player[k]-=v}
 research(id){const u=UPGRADES[id];if(!u||this.player.upgrades.has(id)||(u.requires&&!this.player.upgrades.has(u.requires))||!this.canAfford(u.cost))return false;this.pay(u.cost);this.player.upgrades.add(id);for(const e of this.units.filter(x=>x.team===TEAM.UA)){const before=e.maxHp,after=this.unitStats(e.type).hp;if(after!==before){e.maxHp=after;e.hp=Math.min(after,e.hp+(after-before))}}return true}
 queue(type){const b=this.selectedEntities()[0],t=UNIT_TYPES[type];if(!b||!BUILDING_TYPES[b.type]||!t||t.faction!=='ukraine'||!this.canAfford(t.cost)||this.player.pop+t.pop>this.player.cap)return false;this.pay(t.cost);this.player.pop+=t.pop;b.queue.push({type,left:t.hero?12:t.armor?9:t.air?7:5,reserved:true});return true}
 build(type){const w=this.selectedUnits().find(u=>UNIT_TYPES[u.type].worker),t=BUILDING_TYPES[type];if(!w||!t)return false;const cost=type==='depot'?{metal:100}:type==='barracks'?{metal:150}:{metal:220,fuel:80};if(!this.canAfford(cost))return false;this.pay(cost);const b=this.addBuilding(type,TEAM.UA,w.x+70,w.y+35);b.hp=80;w.order={kind:'construct',target:b};return true}
 useAbility(name){const u=this.selectedUnits()[0];if(!u||!(UNIT_TYPES[u.type].abilities||[]).includes(name)||(u.abilityCd[name]||0)>0)return;const set=n=>u.abilityCd[name]=n;if(name==='reconPulse'){this.effects.push({kind:'recon',x:u.x,y:u.y,radius:430,life:2,max:2});set(20)}else if(name==='fieldDress'){this.units.filter(a=>a.team===u.team&&dist(a,u)<150).forEach(a=>a.hp=Math.min(a.maxHp,a.hp+35));set(12)}else if(name==='rally'||name==='combinedArms'){this.units.filter(a=>a.team===u.team&&dist(a,u)<230).forEach(a=>a.buffs.rally=12);set(name==='rally'?35:38)}else if(name==='address'){this.player.intel+=80;this.units.filter(a=>a.team===u.team).forEach(a=>a.buffs.rally=8);set(50)}else if(name==='deployInfantry'){this.addUnit('uaInfantry',u.team,u.x+30,u.y+30);set(30)}else if(name==='smokeLaunchers'){u.buffs.smoke=8;this.effects.push({kind:'smoke',x:u.x,y:u.y,radius:95,life:8,max:8});set(24)}else if(['grenade','strike','barrage','counterBattery'].includes(name)){const t=this.nearestEnemy(u,name==='barrage'?410:260);if(t){t.hp-=name==='grenade'?45:name==='strike'?90:80;this.effects.push({kind:'blast',x:t.x,y:t.y,radius:70,life:.7,max:.7})}set(name==='grenade'?10:name==='strike'?14:name==='barrage'?24:32)}else if(name==='buildDepot')this.build('depot');else if(name==='buildBarracks')this.build('barracks')}
 nearestEnemy(u,r=(u.team===TEAM.UA?this.unitStats(u.type):UNIT_TYPES[u.type]).sight){let best=null,bd=r;for(const e of [...this.units,...this.buildings])if(e.team!==u.team&&e.hp>0){const d=dist(u,e);if(d<bd){bd=d;best=e}}return best}
 move(u,x,y,dt){const t=u.team===TEAM.UA?this.unitStats(u.type):UNIT_TYPES[u.type],dx=x-u.x,dy=y-u.y,d=Math.hypot(dx,dy);if(d<5)return true;const sp=t.speed*(u.buffs.rally?1.2:1);u.x=clamp(u.x+dx/d*sp*dt,18,WORLD.w-18);u.y=clamp(u.y+dy/d*sp*dt,18,WORLD.h-18);u.angle=Math.atan2(dy,dx);return false}
 shoot(u,t){const s=u.team===TEAM.UA?this.unitStats(u.type):UNIT_TYPES[u.type],d=s.damage;if(!d)return;u.cool=s.rate;let damage=d*(u.buffs.rally?1.25:1);if(t.buffs?.smoke)damage*=.55;if(s.archetype==='drone'&&t.team===TEAM.UA&&this.player.upgrades.has('cageArmor'))damage*=.75;this.projectiles.push({x:u.x,y:u.y-8,target:t,team:u.team,speed:s.armor?250:330,damage,life:2,kind:s.armor?'shell':'bullet'});u.flash=.1}
 updateUnit(u,dt){const t=u.team===TEAM.UA?this.unitStats(u.type):UNIT_TYPES[u.type];u.cool-=dt;u.flash=Math.max(0,u.flash-dt);for(const k in u.abilityCd)u.abilityCd[k]=Math.max(0,u.abilityCd[k]-dt);for(const k in u.buffs){u.buffs[k]-=dt;if(u.buffs[k]<=0)delete u.buffs[k]}if(t.worker&&u.team===TEAM.UA){if(u.order?.kind==='gather'){const n=u.order.target;if(n.amount>0&&dist(u,n)<35){u.carry=Math.min(40,u.carry+18*dt);u.carryKind=n.kind;n.amount-=18*dt;if(u.carry>=40)u.order={kind:'return',target:this.uaHQ}}else this.move(u,n.x,n.y,dt)}else if(u.order?.kind==='return'){if(dist(u,this.uaHQ)<70){this.player[u.carryKind]+=u.carry;this.player.mined+=u.carry;u.carry=0;const n=this.nodes.filter(n=>n.kind===u.carryKind&&n.amount>0).sort((a,b)=>dist(a,u)-dist(b,u))[0];if(n)u.order={kind:'gather',target:n}}else this.move(u,this.uaHQ.x,this.uaHQ.y,dt)}else if(!u.order){const n=this.nodes.filter(n=>n.amount>0).sort((a,b)=>dist(a,u)-dist(b,u))[0];if(n)u.order={kind:'gather',target:n}}if(u.order?.kind==='construct'){const b=u.order.target;if(dist(u,b)>55)this.move(u,b.x,b.y,dt);else{b.hp=Math.min(b.maxHp,b.hp+90*dt);if(b.hp>=b.maxHp)u.order=null}}}if(t.medic){const a=this.units.filter(a=>a.team===u.team&&a.hp<a.maxHp&&dist(a,u)<t.range).sort((a,b)=>a.hp/a.maxHp-b.hp/b.maxHp)[0];if(a&&u.cool<=0){a.hp=Math.min(a.maxHp,a.hp+12);u.cool=t.rate}}let target=u.order?.kind==='attack'&&u.order.target?.hp>0?u.order.target:null;if(!target&&(u.order?.kind==='attackMove'||u.team===TEAM.RU))target=this.nearestEnemy(u);if(target){const d=dist(u,target);if(d<=t.range){u.angle=Math.atan2(target.y-u.y,target.x-u.x);if(u.cool<=0)this.shoot(u,target)}else this.move(u,target.x,target.y,dt)}else if(u.order&&(u.order.kind==='move'||u.order.kind==='attackMove')){if(this.move(u,u.order.x,u.order.y,dt))u.order=null}}
 updateProjectiles(dt){for(const p of this.projectiles){p.life-=dt;const t=p.target;if(!t||t.hp<=0){p.life=0;continue}const dx=t.x-p.x,dy=t.y-p.y,d=Math.hypot(dx,dy);if(d<p.speed*dt+7){t.hp-=p.damage;p.life=0;this.effects.push({kind:'blast',x:t.x,y:t.y,radius:45,life:.45,max:.45})}else{p.x+=dx/d*p.speed*dt;p.y+=dy/d*p.speed*dt}}this.projectiles=this.projectiles.filter(p=>p.life>0)}
 spawnWave(){this.wave++;const pools=[['ruInfantry','ruInfantry','ruEngineer'],['ruInfantry','ruIfv','ruMedic'],['ruInfantry','ruDrone','ruTank'],['ruInfantry','ruIfv','ruArtillery','ruTank']];const list=pools[Math.min(pools.length-1,Math.floor((this.wave-1)/2))].slice();if(this.mission.id==='kherson'&&this.wave%2===0)list.push('ruTank','ruInfantry');for(let i=0;i<list.length;i++){const u=this.addUnit(list[i],TEAM.RU,this.ruHQ.x-100-i*34,this.ruHQ.y+100+i*24);u.order={kind:'attackMove',x:this.uaHQ.x,y:this.uaHQ.y}}}
 updateObjectives(){if(this.mission.id==='donbas'){this.player.objectives[0]=this.player.mined>=500;this.player.objectives[1]=this.buildings.some(b=>b.team===TEAM.UA&&b.type==='workshop')&&this.buildings.some(b=>b.team===TEAM.UA&&b.type==='barracks');this.player.objectives[2]=!this.buildings.includes(this.ruHQ)}else if(this.mission.id==='zaporizhzhia'){this.player.objectives[0]=this.player.intel>=250;this.player.objectives[1]=this.units.filter(u=>u.team===TEAM.UA&&u.type==='uaDrone').length>=4;this.player.objectives[2]=!this.units.some(u=>u.team===TEAM.RU&&u.type==='ruArtillery')}else{this.player.objectives[0]=['uaZelenskyy','uaZaluzhnyi'].every(h=>this.units.some(u=>u.team===TEAM.UA&&u.type===h));this.player.objectives[1]=this.wave>=6;this.player.objectives[2]=!this.buildings.includes(this.ruHQ)}}
 update(dt){if(this.gameOver)return;this.time+=dt;const pan=400*dt;if(this.keys.has('arrowup')||this.keys.has('w'))this.camera.y+=pan;if(this.keys.has('arrowdown'))this.camera.y-=pan;if(this.keys.has('arrowleft'))this.camera.x+=pan;if(this.keys.has('arrowright')||this.keys.has('d'))this.camera.x-=pan;this.camera.x=clamp(this.camera.x,innerWidth-WORLD.w*this.camera.z-100,100);this.camera.y=clamp(this.camera.y,innerHeight-WORLD.h*this.camera.z-180,100);for(const u of this.units)this.updateUnit(u,dt);this.updateProjectiles(dt);for(const b of this.buildings)if(b.queue.length){b.queue[0].left-=dt;if(b.queue[0].left<=0){const q=b.queue.shift();this.addUnit(q.type,b.team,b.x+rand(-70,70),b.y+85);if(q.reserved)this.player.pop-=UNIT_TYPES[q.type].pop}}this.enemy.clock-=dt;if(this.enemy.clock<=0){this.enemy.clock=this.mission.id==='kherson'?12:17;this.spawnWave()}this.units=this.units.filter(u=>{if(u.hp>0)return true;if(u.team===TEAM.UA)this.player.pop-=UNIT_TYPES[u.type].pop||0;this.selected.delete(u.id);return false});this.buildings=this.buildings.filter(b=>{if(b.hp>0)return true;if(b.team===TEAM.UA)this.player.cap-=BUILDING_TYPES[b.type].pop||0;this.selected.delete(b.id);return false});this.updateObjectives();if(this.player.objectives.every(Boolean)||!this.buildings.includes(this.uaHQ))this.gameOver=true}
}