import {TEAM,WORLD,UNIT_TYPES,BUILDING_TYPES} from './config.js';
const C={ua:'#2f70aa',ua2:'#f1d35f',ru:'#8f4038',ru2:'#d0bd9d',dark:'#222820',shadow:'rgba(0,0,0,.38)'};
export class Renderer{
 constructor(game,canvas,minimap,portrait){this.g=game;this.c=canvas;this.x=canvas.getContext('2d');this.m=minimap;this.mx=minimap.getContext('2d');this.p=portrait;this.px=portrait.getContext('2d');this.fogCanvas=document.createElement('canvas');this.fx=this.fogCanvas.getContext('2d');this.resize();addEventListener('resize',()=>this.resize())}
 resize(){this.dpr=Math.min(2,devicePixelRatio||1);this.c.width=innerWidth*this.dpr;this.c.height=innerHeight*this.dpr;this.c.style.width=innerWidth+'px';this.c.style.height=innerHeight+'px';this.x.setTransform(this.dpr,0,0,this.dpr,0,0);this.x.imageSmoothingEnabled=false;this.fogCanvas.width=innerWidth;this.fogCanvas.height=innerHeight}
 sp(x,y){return{x:x*this.g.camera.z+this.g.camera.x,y:y*this.g.camera.z+this.g.camera.y}}
 tileColor(t,x,y){if(t===2)return(x+y)%3?'#3d4e32':'#46593a';if(t===1)return(x+y)%2?'#6b6e57':'#74765d';return(x*5+y*7)%6?'#6d764a':'#768050'}
 terrain(){const q=this.x,z=this.g.camera.z,a=this.g.worldPos(0,0),b=this.g.worldPos(innerWidth,innerHeight);for(let y=Math.max(0,Math.floor(a.y/32)-1);y<Math.min(WORLD.h/32,Math.ceil(b.y/32)+1);y++)for(let x=Math.max(0,Math.floor(a.x/32)-1);x<Math.min(WORLD.w/32,Math.ceil(b.x/32)+1);x++){const t=this.g.terrain[y*(WORLD.w/32)+x],s=this.sp(x*32,y*32);q.fillStyle=this.tileColor(t,x,y);q.fillRect(s.x,s.y,33*z,33*z);if(t===2&&(x*11+y*17)%7===0){q.fillStyle='#263622';q.fillRect(s.x+12*z,s.y+7*z,6*z,20*z);q.fillStyle='#425b35';q.fillRect(s.x+4*z,s.y+1*z,23*z,15*z)}if(t===1&&(x+y)%9===0){q.fillStyle='#8e8b70';q.fillRect(s.x+7*z,s.y+18*z,13*z,6*z)}}q.strokeStyle='#8e805e';q.lineWidth=46*z;q.lineCap='square';q.beginPath();this.g.road.forEach((p,i)=>{const s=this.sp(p[0],p[1]);i?q.lineTo(s.x,s.y):q.moveTo(s.x,s.y)});q.stroke();q.strokeStyle='#655d49';q.lineWidth=4*z;q.setLineDash([15*z,18*z]);q.stroke();q.setLineDash([])}
 resourceNode(n){const q=this.x,s=this.sp(n.x,n.y),z=this.g.camera.z;q.save();q.translate(s.x,s.y);q.fillStyle=n.kind==='metal'?'#767873':n.kind==='fuel'?'#4d3e2f':'#62547d';q.strokeStyle=n.amount>0?'#d6c17a':'#555';q.lineWidth=3;q.beginPath();q.arc(0,0,25*z,0,Math.PI*2);q.fill();q.stroke();q.fillStyle=n.kind==='metal'?'#b8bbb6':n.kind==='fuel'?'#d7a84c':'#bda8e0';for(let i=0;i<5;i++)q.fillRect((-14+i*7)*z,(-10+(i%2)*9)*z,5*z,12*z);q.restore()}
 building(b){const q=this.x,s=this.sp(b.x,b.y),z=this.g.camera.z,t=BUILDING_TYPES[b.type],w=t.w*z,h=t.h*z;q.save();q.translate(s.x,s.y);q.fillStyle=C.shadow;q.fillRect(-w*.52,-h*.32,w*1.08,h*.86);q.fillStyle=b.team===TEAM.UA?C.ua:C.ru;q.fillRect(-w/2,-h/2,w,h);q.fillStyle='#9b8c63';q.fillRect(-w*.42,-h*.42,w*.84,h*.23);q.fillStyle='#232921';q.fillRect(-11*z,-5*z,22*z,h*.52);q.fillStyle=b.team===TEAM.UA?C.ua2:C.ru2;q.fillRect(-w*.35,-h*.28,w*.22,h*.15);for(let i=-1;i<=1;i++){q.fillStyle='#aa9a70';q.fillRect((i*27-8)*z,-h*.62,16*z,20*z)}if(b.type==='workshop'){q.fillStyle='#202720';q.fillRect(-w*.34,4*z,w*.68,h*.25)}if(b.selected){q.strokeStyle='#ffe47a';q.lineWidth=3;q.strokeRect(-w/2-5,-h/2-5,w+10,h+10)}this.health(b,-w/2,-h/2-11,w);q.restore()}
 unit(u){const q=this.x,t=UNIT_TYPES[u.type],s=this.sp(u.x,u.y),z=this.g.camera.z;q.save();q.translate(Math.round(s.x),Math.round(s.y));if(t.air){q.globalAlpha=.25;q.fillStyle='#000';q.beginPath();q.ellipse(8*z,12*z,17*z,8*z,0,0,Math.PI*2);q.fill();q.globalAlpha=1;q.rotate(u.angle);q.fillStyle=u.team===TEAM.UA?C.ua:C.ru;q.fillRect(-15*z,-4*z,30*z,8*z);q.fillStyle=C.dark;q.fillRect(-4*z,-13*z,8*z,26*z);q.fillStyle=u.team===TEAM.UA?C.ua2:C.ru2;q.fillRect(-2*z,-2*z,4*z,4*z);q.restore();this.selection(u,s,t,z);return}q.fillStyle=C.shadow;q.beginPath();q.ellipse(3*z,8*z,(t.size+5)*z,(t.size*.58)*z,0,0,Math.PI*2);q.fill();q.rotate(u.angle+Math.PI/2);const body=u.team===TEAM.UA?C.ua:C.ru;if(t.armor){q.fillStyle=body;q.fillRect(-17*z,-18*z,34*z,36*z);q.fillStyle='#283029';q.fillRect(-11*z,-21*z,22*z,23*z);q.fillRect(-3*z,-34*z,6*z,22*z);if(u.type==='artillery')q.fillRect(-2*z,-45*z,4*z,30*z)}else{q.fillStyle=body;q.fillRect(-8*z,-7*z,16*z,20*z);q.fillStyle=u.team===TEAM.UA?C.ua2:C.ru2;q.beginPath();q.arc(0,-10*z,6*z,0,Math.PI*2);q.fill();q.fillStyle='#242b25';if(t.medic){q.fillStyle='#e2e4da';q.fillRect(-6*z,-2*z,12*z,11*z);q.fillStyle='#a33';q.fillRect(-2*z,-1*z,4*z,9*z);q.fillRect(-5*z,2*z,10*z,3*z)}else if(t.hero){q.fillStyle='#d9b94e';q.fillRect(-10*z,-3*z,20*z,4*z);q.fillStyle='#242924';q.fillRect(-2*z,-25*z,4*z,20*z)}else if(t.worker){q.fillStyle='#c28b43';q.fillRect(-8*z,-2*z,16*z,6*z);q.fillStyle='#2a3028';q.fillRect(-2*z,-22*z,4*z,18*z)}else q.fillRect(-2*z,-22*z,4*z,20*z)}if(u.flash){q.fillStyle='#fff0a5';q.beginPath();q.arc(0,-29*z,5*z,0,Math.PI*2);q.fill()}q.restore();this.selection(u,s,t,z)}
 selection(u,s,t,z){const q=this.x;if(u.selected){q.strokeStyle='#ffe47b';q.lineWidth=2;q.beginPath();q.ellipse(s.x,s.y+6*z,(t.size+8)*z,(t.size*.65+5)*z,0,0,Math.PI*2);q.stroke()}if(u.hp<u.maxHp)this.health(u,s.x-17*z,s.y-27*z,34*z)}
 health(e,x,y,w){const q=this.x;q.fillStyle='#211815';q.fillRect(x,y,w,5);q.fillStyle=e.team===TEAM.UA?'#69a9dc':'#ca5d54';q.fillRect(x,y,w*Math.max(0,e.hp/e.maxHp),5)}
 effects(){const q=this.x,z=this.g.camera.z;for(const p of this.g.projectiles){const s=this.sp(p.x,p.y);q.fillStyle=p.kind==='shell'?'#ffb84d':'#fff1b0';q.beginPath();q.arc(s.x,s.y,p.kind==='shell'?4:2,0,Math.PI*2);q.fill()}for(const e of this.g.effects){const s=this.sp(e.x,e.y);q.globalAlpha=Math.max(0,e.life/e.max);q.strokeStyle=e.kind==='recon'?'#7ec8ff':'#f2d36e';q.lineWidth=3;q.beginPath();q.arc(s.x,s.y,(1-e.life/e.max)*e.radius*z,0,Math.PI*2);q.stroke();q.globalAlpha=1}}
 fog(){const q=this.fx,z=this.g.camera.z;q.clearRect(0,0,innerWidth,innerHeight);q.fillStyle='rgba(6,9,8,.68)';q.fillRect(0,0,innerWidth,innerHeight);q.globalCompositeOperation='destination-out';for(const e of [...this.g.units,...this.g.buildings])if(e.team===TEAM.UA){const s=this.sp(e.x,e.y),r=((UNIT_TYPES[e.type]?.sight)||(BUILDING_TYPES[e.type]?.sight)||180)*z,g=q.createRadialGradient(s.x,s.y,r*.32,s.x,s.y,r);g.addColorStop(0,'rgba(0,0,0,1)');g.addColorStop(1,'rgba(0,0,0,0)');q.fillStyle=g;q.beginPath();q.arc(s.x,s.y,r,0,Math.PI*2);q.fill()}q.globalCompositeOperation='source-over';this.x.drawImage(this.fogCanvas,0,0)}
 mini(){const q=this.mx;q.fillStyle='#596443';q.fillRect(0,0,220,138);q.strokeStyle='#8f8060';q.lineWidth=4;q.beginPath();this.g.road.forEach((p,i)=>{const x=p[0]/WORLD.w*220,y=p[1]/WORLD.h*138;i?q.lineTo(x,y):q.moveTo(x,y)});q.stroke();for(const n of this.g.nodes){q.fillStyle=n.kind==='metal'?'#bbb':n.kind==='fuel'?'#d7a84c':'#bda8e0';q.fillRect(n.x/WORLD.w*220-2,n.y/WORLD.h*138-2,4,4)}for(const b of this.g.buildings){q.fillStyle=b.team===TEAM.UA?'#64acf0':'#d86359';q.fillRect(b.x/WORLD.w*220-4,b.y/WORLD.h*138-4,8,8)}for(const u of this.g.units){q.fillStyle=u.team===TEAM.UA?'#89c9fa':'#ee7469';q.fillRect(u.x/WORLD.w*220,u.y/WORLD.h*138,2,2)}const a=this.g.worldPos(0,0),b=this.g.worldPos(innerWidth,innerHeight);q.strokeStyle='#fff3a4';q.strokeRect(a.x/WORLD.w*220,a.y/WORLD.h*138,(b.x-a.x)/WORLD.w*220,(b.y-a.y)/WORLD.h*138)}
 portrait(e){const q=this.px;q.clearRect(0,0,144,112);q.fillStyle='#182018';q.fillRect(0,0,144,112);if(!e)return;const team=e.team===TEAM.UA?C.ua:C.ru;q.fillStyle='#394437';for(let y=0;y<112;y+=16)for(let x=0;x<144;x+=16)if((x+y)%32===0)q.fillRect(x,y,16,16);q.fillStyle=team;q.fillRect(39,43,66,53);q.fillStyle=e.team===TEAM.UA?C.ua2:C.ru2;q.fillRect(50,20,44,40);q.fillStyle='#222';q.fillRect(57,34,8,6);q.fillRect(80,34,8,6);q.fillRect(65,49,18,5);if(UNIT_TYPES[e.type]?.hero){q.fillStyle='#d7b84c';q.fillRect(44,61,56,8)}q.strokeStyle='#a58a51';q.lineWidth=5;q.strokeRect(2,2,140,108)}
 render(){this.x.clearRect(0,0,innerWidth,innerHeight);this.terrain();this.g.nodes.forEach(n=>this.resourceNode(n));this.g.buildings.slice().sort((a,b)=>a.y-b.y).forEach(b=>this.building(b));this.g.units.slice().sort((a,b)=>a.y-b.y).forEach(u=>this.unit(u));this.effects();this.fog();this.mini();this.portrait(this.g.selectedEntities()[0])}
}