import { readFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import {
  UI_SKIN,
  UI_SKIN_ASSET_CSS_PATH,
  UI_SKIN_SOURCE_PATH,
  UI_SKIN_STYLESHEET_PATH,
  buildUiSkinAssetCss,
  validateUiSkin,
} from '../src/ui/ui-skin.js';

const projectRoot = resolve(fileURLToPath(new URL('..', import.meta.url)));
const read = (path) => readFile(resolve(projectRoot, path), 'utf8');
const fail = (message) => { throw new Error(message); };

validateUiSkin();

const [sourceText, generatedCss, skinCss, indexHtml] = await Promise.all([
  read(UI_SKIN_SOURCE_PATH),
  read(UI_SKIN_ASSET_CSS_PATH),
  read(UI_SKIN_STYLESHEET_PATH),
  read('index.html'),
]);

const source = JSON.parse(sourceText);
if (source.schema !== 'fields-of-resolve.ui-skin-source' || source.version !== 1) fail('UI skin source manifest schema is invalid.');
if (source.authority !== 'src/ui/ui-skin.js') fail('UI skin source authority drifted.');
if (source.provenance?.license !== 'CC0-1.0' || source.provenance?.externalInputs?.length !== 0) fail('UI skin provenance is incomplete.');
if (source.provenance?.embeddedText !== false) fail('Reusable UI skin assets must not embed player-facing text.');
if (source.nineSliceAssets?.length !== UI_SKIN.assets.length) fail('UI skin source asset count drifted.');

const expectedCss = buildUiSkinAssetCss();
if (generatedCss !== expectedCss) fail(`${UI_SKIN_ASSET_CSS_PATH} is stale; run node scripts/build-ui-skin.mjs.`);

const assetLink = `<link rel="stylesheet" href="${UI_SKIN_ASSET_CSS_PATH}" />`;
const skinLink = `<link rel="stylesheet" href="${UI_SKIN_STYLESHEET_PATH}" />`;
if (!indexHtml.includes(assetLink) || !indexHtml.includes(skinLink)) fail('Active index.html does not load both UI skin stylesheets.');
if (indexHtml.indexOf(assetLink) > indexHtml.indexOf(skinLink)) fail('UI skin asset variables must load before UI skin rules.');

const requiredPatterns = [
  ['nine-slice panel', /border-image-slice:\s*12\s+fill/],
  ['nine-slice control', /border-image-slice:\s*9\s+fill/],
  ['top bar', /#topbar/],
  ['command panel', /#commandPanel/],
  ['mission screen', /\.book/],
  ['button states', /button:hover/],
  ['focus state', /:focus-visible/],
  ['disabled state', /:disabled/],
  ['tooltip skin', /\[data-tooltip\]/],
  ['scrollbar skin', /::-webkit-scrollbar-thumb/],
  ['reduced motion', /prefers-reduced-motion:\s*reduce/],
  ['high contrast', /prefers-contrast:\s*more/],
];
for (const [label, pattern] of requiredPatterns) {
  if (!pattern.test(skinCss)) fail(`UI skin stylesheet is missing ${label}.`);
}

for (const component of UI_SKIN.components) {
  if (!skinCss.includes(component.selector)) fail(`UI skin stylesheet does not cover ${component.selector}.`);
}

process.stdout.write(
  `[ui-skin] verified ${UI_SKIN.assets.length} scalable nine-slice assets, `
  + `${UI_SKIN.components.length} component mappings, ${generatedCss.length} generated bytes, active runtime links, states, scrollbars, reduced motion, and high contrast\n`,
);
